### ISSUE TITLE
define path in load_standard_voxel_grid

### ISSUE THREAD

**Issue by ciozzaman** [cherab/mastu#11]
I have my geometry file in a certain location an I would like to point at that when I use
load_standard_voxel_grid
in
cherab_mastu/cherab/mastu/bolometry/grid_construction/load_voxel_grids.py

an argument
path=None
and
if path==None: ecc. 
would be backward compatible and do the trick.

Thanks

**Comment by jacklovell** [comment]
Fixed in a65583a
